### ISSUE TITLE
Game won't start anymore

### ISSUE THREAD

**Issue by roman-bronis** [ValveSoftware/portal2#173]
Today I tried to run game but it won't start anymore (it was working few days back).

Debugging info:

```
[john@john-pc Portal 2]$ gdb --args /home/john/.local/share/Steam/SteamApps/common/Portal\ 2/portal2_linux -game portal2 -steam
gdb: Symbol `acs_map' has different size in shared object, consider re-linking
GNU gdb (GDB) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/john/.local/share/Steam/SteamApps/common/Portal 2/portal2_linux...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/john/.local/share/Steam/SteamApps/common/Portal 2/portal2_linux -game portal2 -steam
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0xf7516b40 (LWP 25218)]
[New Thread 0xf7415b40 (LWP 25219)]
[New Thread 0xf7314b40 (LWP 25220)]
[New Thread 0xf7213b40 (LWP 25221)]
SDL video target is 'x11'
SDL video target is 'x11'

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.

Program received signal SIGSEGV, Segmentation fault.
0xf2a8e1a0 in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/vguimatsurface.so
(gdb) bt
#0  0xf2a8e1a0 in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/vguimatsurface.so
#1  0xf2a21b57 in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/vguimatsurface.so
#2  0xf7feb00e in call_init.part () from /lib/ld-linux.so.2
#3  0xf7feb104 in _dl_init_internal () from /lib/ld-linux.so.2
#4  0xf7fef1ce in dl_open_worker () from /lib/ld-linux.so.2
#5  0xf7feaeb6 in _dl_catch_error () from /lib/ld-linux.so.2
#6  0xf7fee9c4 in _dl_open () from /lib/ld-linux.so.2
#7  0xf7f92cbc in ?? () from /usr/lib32/libdl.so.2
#8  0xf7feaeb6 in _dl_catch_error () from /lib/ld-linux.so.2
#9  0xf7f9337c in ?? () from /usr/lib32/libdl.so.2
#10 0xf7f92d71 in dlopen () from /usr/lib32/libdl.so.2
#11 0xf7580554 in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/filesystem_stdio.so
#12 0xf7580679 in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/filesystem_stdio.so
#13 0xf7580918 in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/filesystem_stdio.so
#14 0xf754acab in ?? () from /home/john/.local/share/Steam/SteamApps/common/Portal 2/bin/filesystem_stdio.so
#15 0xf7c659cb in ?? () from bin/launcher.so
#16 0xf7c66cf6 in ?? () from bin/launcher.so
#17 0xf7c67936 in ?? () from bin/launcher.so
#18 0xf7c4a11e in ?? () from bin/launcher.so
#19 0xf7c67814 in ?? () from bin/launcher.so
#20 0xf7c678bd in ?? () from bin/launcher.so
#21 0xf7c678f0 in ?? () from bin/launcher.so
#22 0xf7c4b373 in LauncherMain () from bin/launcher.so
#23 0x08048564 in main ()
```

System info: (i5 2500K, 8GB RAM, HD 6870 with Catalyst driver, Arch 64bit)

```
    Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  Fluxbox
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series 

    Driver Version:  4.3.12795 Compatibility Profile Context 13.101
    OpenGL Version: 4.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6738
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.82" x 10.59"  (21.57" diag)
                                            47.8cm x 26.9cm  (54.8cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7966 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  74966 Mb
    Largest Free Hard Disk Block:  3051 Mb

Installed software:

Recent Failure Reports:
```

**Comment by davidw-valve** [comment]
Does the game start with the latest update? What if you remove it and reinstall it?

**Comment by roman-bronis** [comment]
It's working after last update. Thank you.
