### ISSUE TITLE
Portal 2 crashes on startup tcmalloc::CentralFreeList::RemoveRange

### ISSUE THREAD

**Issue by lazyfrosch** [ValveSoftware/portal2#260]
I'm on Debian stretch (testing)

Portal 2 worked fine until Sunday, now it crashes with a SIGSEGV:

```
LD_LIBRARY_PATH="`pwd`/bin" gdb --args ./portal2_linux -game portal2

GNU gdb (Debian 7.10-1) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./portal2_linux...(no debugging symbols found)...done.
(gdb) run
Starting program: /data/games/SteamLibrary/steamapps/common/Portal 2/portal2_linux -game portal2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0xf74d0b40 (LWP 8412)]
[New Thread 0xf73cfb40 (LWP 8413)]
[New Thread 0xf72ceb40 (LWP 8414)]
[New Thread 0xf71cdb40 (LWP 8415)]
SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Using breakpad crash handler
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Did not detect any valid joysticks.
Did not detect any valid joysticks.

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

[New Thread 0xf42e0b40 (LWP 8417)]
[New Thread 0xeff35b40 (LWP 8418)]
[Thread 0xeff35b40 (LWP 8418) exited]
[New Thread 0xeff35b40 (LWP 8419)]
[New Thread 0xf423eb40 (LWP 8420)]

Program received signal SIGSEGV, Segmentation fault.
tcmalloc::CentralFreeList::RemoveRange (this=0xf7fcb320 <tcmalloc::Static::central_cache_+27520>, start=0xffffbda8, end=0xffffbdac, 
    N=13) at src/central_freelist.cc:271
271 src/central_freelist.cc: No such file or directory.
(gdb) bt
#0  tcmalloc::CentralFreeList::RemoveRange (this=0xf7fcb320 <tcmalloc::Static::central_cache_+27520>, start=0xffffbda8, 
    end=0xffffbdac, N=13) at src/central_freelist.cc:271
#1  0xf7fa944e in tcmalloc::ThreadCache::FetchFromCentralCache (this=0x80cb900, cl=43, byte_size=4096) at src/thread_cache.cc:162
#2  0xf7fb0ae5 in tcmalloc::ThreadCache::Allocate (cl=<optimized out>, size=4096, this=0x80cb900) at src/thread_cache.h:341
#3  (anonymous namespace)::do_malloc (size=4096) at src/tcmalloc.cc:1068
#4  (anonymous namespace)::do_malloc_or_cpp_alloc (size=3360) at src/tcmalloc.cc:1005
#5  (anonymous namespace)::do_calloc (elem_size=3360, n=1) at src/tcmalloc.cc:1082
#6  tc_calloc (n=1, elem_size=3360) at src/tcmalloc.cc:1504
#7  0xf64cd8fb in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#8  0xf64cd278 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#9  0xf6691f13 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#10 0xf668e8e0 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#11 0xf668fc12 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#12 0xf68a85a6 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#13 0xf64d4c83 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#14 0xf64d4f38 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#15 0xf76d5bf1 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/libtogl.so
#16 0xf76d6345 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/libtogl.so
#17 0xf76c6f3b in IDirect3DDevice9::Present(_RECT const*, _RECT const*, void*, RGNDATA const*) ()
   from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/libtogl.so
#18 0xf460695d in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/shaderapidx9.so
#19 0xf54a70ee in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/materialsystem.so
#20 0xf5d80eb2 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#21 0xf5d80326 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#22 0xf5d7fc63 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#23 0xf5d7dd05 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#24 0xf5d7e60f in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#25 0xf5d78546 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#26 0xf5d798a0 in ?? () from /data/games/SteamLibrary/steamapps/common/Portal 2/bin/engine.so
#27 0xf7c3fc00 in ?? () from bin/launcher.so
#28 0xf7c3fc00 in ?? () from bin/launcher.so
#29 0xf7c2341a in LauncherMain () from bin/launcher.so
#30 0x08048564 in main ()

```

**Comment by davidw-valve** [comment]
Should be fixed.

**Comment by lazyfrosch** [comment]
@davidw-valve wow that was fast, thanks a lot!
